### ISSUE TITLE
invalid version 

### ISSUE THREAD

**Issue by barisusakli** [Jenkler/nodebb-widget-rss#2]
the version in package.json throws an error during ./nodebb upgrade

more info

https://github.com/NodeBB/NodeBB/issues/12009

might have to republish with a 3.2.2, not sure why `3.2.00001` was used.

**Comment by Jenkler** [comment]
Will 3.2.10002 work? I think I had this issue before. Can you verify that 3.2.10002 will work?

**Comment by barisusakli** [comment]
@Jenkler, semver.valid to the rescue.

```
res.json({
	'3.2.1': semver.valid('3.2.1'),
	'3.2.00001': semver.valid('3.2.00001'),
	'3.2.10002': semver.valid('3.2.10002'),
});
```
result
```
{
    "3.2.1": "3.2.1",
    "3.2.00001": null,
    "3.2.10002": "3.2.10002"
}
```

So yeah 3.2.10002 seems valid.

**Comment by Jenkler** [comment]
I have now fixed npm publish with the new version. Please notify me if this solves the issue!

**Comment by barisusakli** [comment]
👍🏼 looks good
